GET http://localhost:1337/todos

###

GET http://localhost:1337/todos/1

###

GET http://localhost:1337/todos/15555

###

DELETE  http://localhost:1337/todos/1

###

POST   http://localhost:1337/todos
Content-Type: application/json

{
    "completed": true,
    "title": "manger"
}

###

PUT   http://localhost:1337/todos/3
Content-Type: application/json

{
    "completed": true
}
